version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser          # PostgreSQL user
      POSTGRES_PASSWORD: mypassword  # PostgreSQL password
      POSTGRES_DB: mydatabase       # Database name to create
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    ports:
      - "5432:5432"                 # Expose PostgreSQL port

volumes:
  postgres_data:

